name: build and deploy web api to azure

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    outputs:
      short_sha: ${{ steps.vars.outputs.short_sha }}
    steps:
      - name: checkout repository
        id: github
        uses: actions/checkout@v4

      - name: setup web api .net
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: configure azure acr
        uses: azure/docker-login@v2
        with:
          login-server: ${{vars.ACR_SERVER}}
          username: ${{secrets.ACR_USER_NAME}}
          password: ${{secrets.ACR_USER_PASS}}

      - name: sha form commit
        id: vars
        run: |
          echo "short_sha=$(git rev-parse --short ${{github.sha}})" >> "$GITHUB_OUTPUT"
      - name: build and push docker image to acr
        env:
          ACR_REGISTRY: ${{vars.ACR_SERVER}}
          IMAGE_TAG: ${{steps.vars.outputs.short_sha}}
        run: |
          docker build -f api_net.dockerfile \
          -t $ACR_REGISTRY/netapp:$IMAGE_TAG \
          -t $ACR_REGISTRY/netapp:latest \
          .
          docker push $ACR_REGISTRY/netapp --all-tags

  deploy-app-to-aca:
    runs-on: ubuntu-latest
    needs: build-and-deploy

    steps:
      - name: login to azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZURE_CREDENTIALS}}

      - name: deploy to aca
        uses: azure/container-apps-deploy-action@v1
        env:
          IMAGE_TAG: ${{needs.build-and-deploy.outputs.short_sha}}
          ACR_SERVER: ${{vars.ACR_SERVER}}
        with:
          registryUrl: ${{ vars.ACR_SERVER }}
          imageToDeploy: $ACR_SERVER/app$IMAGE_TAG
          targetPort: 8080
          ingress: external
          containerAppName: aca-api-net
          containerAppEnvironment: azc-api-net-Environment
          resourceGroup: rg_api_net
          environmentVariables: |
            ASPNETCORE_ENVIRONMENT=Development ASPNETCORE_URLS=http//+:8080
